### ISSUE TITLE
Basic command request example ends up in segfault

### ISSUE THREAD

**Issue by marek-cerny** [strongswan/govici#6]
Hello.

The very 1st example from the readme isn't workig:
```
daemon: charon-systemd
version: 5.7.2
sysname: Linux
release: 4.19.0-6-amd64
machine: x86_64
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x531840]

goroutine 1 [running]:
github.com/strongswan/govici.(*eventListener).Close(0x0, 0xc0000ae000, 0xc000040eb8)
        /root/go/src/github.com/strongswan/govici/events.go:75 +0x20
github.com/strongswan/govici.(*Session).Close(0xc000078630, 0x0, 0x2)
        /root/go/src/github.com/strongswan/govici/session.go:76 +0x33
main.main()
        /root/go/src/gitlab.oubcom.net/linux/nagios-plugins/nrpe/check_swan_cert/main.go:126 +0x2fc
```
It seems to be caused by an attempt to `Close()` the `Session`, which in turn tries to `Close()` the `eventListener`. As there is no `eventListener` registered at this point, the program crashes.

Quick hack in the `Close()` function in `session.go` seems to resolve the issue:
```
if s.el != nil {
  if err := s.el.Close(); err != nil {
    return err
  }
}
```

**Comment by enr0n** [comment]
Thanks for reporting this. I failed to add a test case for `session.Close` where no event listener has been registered. I will push a fix shortly.
